spring.application.name=j2ee16

spring.datasource.url=jdbc:postgresql://ep-raspy-heart-a138tcbg-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WAXgekE04Ucf
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.flyway.enabled=false

# JWT
security.jwt.secret=mysupersecretkeymysupersecretkey123456
security.jwt.access-token-ttl-seconds=900
security.jwt.refresh-token-ttl-seconds=604800
security.jwt.issuer=bus-booking

# Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

springdoc.swagger-ui.path=/swagger-ui.html