-- Auto-generated script to seed provinces
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Thành phố Hà Nội', 'thanh_pho_ha_noi', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Hà Giang', 'tinh_ha_giang', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Cao Bằng', 'tinh_cao_bang', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Bắc Kạn', 'tinh_bac_kan', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Tuyên Quang', 'tinh_tuyen_quang', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Lào Cai', 'tinh_lao_cai', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Điện Biên', 'tinh_dien_bien', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Lai Châu', 'tinh_lai_chau', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Sơn La', 'tinh_son_la', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Yên Bái', 'tinh_yen_bai', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Hoà Bình', 'tinh_hoa_binh', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Thái Nguyên', 'tinh_thai_nguyen', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Lạng Sơn', 'tinh_lang_son', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Quảng Ninh', 'tinh_quang_ninh', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Bắc Giang', 'tinh_bac_giang', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Phú Thọ', 'tinh_phu_tho', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Vĩnh Phúc', 'tinh_vinh_phuc', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Bắc Ninh', 'tinh_bac_ninh', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Hải Dương', 'tinh_hai_duong', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Thành phố Hải Phòng', 'thanh_pho_hai_phong', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Hưng Yên', 'tinh_hung_yen', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Thái Bình', 'tinh_thai_binh', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Hà Nam', 'tinh_ha_nam', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Nam Định', 'tinh_nam_dinh', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Ninh Bình', 'tinh_ninh_binh', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Thanh Hóa', 'tinh_thanh_hoa', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Nghệ An', 'tinh_nghe_an', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Hà Tĩnh', 'tinh_ha_tinh', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Quảng Bình', 'tinh_quang_binh', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Quảng Trị', 'tinh_quang_tri', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Thành phố Huế', 'thanh_pho_hue', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Thành phố Đà Nẵng', 'thanh_pho_da_nang', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Quảng Nam', 'tinh_quang_nam', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Quảng Ngãi', 'tinh_quang_ngai', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Bình Định', 'tinh_binh_dinh', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Phú Yên', 'tinh_phu_yen', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Khánh Hòa', 'tinh_khanh_hoa', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Ninh Thuận', 'tinh_ninh_thuan', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Bình Thuận', 'tinh_binh_thuan', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Kon Tum', 'tinh_kon_tum', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Gia Lai', 'tinh_gia_lai', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Đắk Lắk', 'tinh_dak_lak', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Đắk Nông', 'tinh_dak_nong', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Lâm Đồng', 'tinh_lam_dong', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Bình Phước', 'tinh_binh_phuoc', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Tây Ninh', 'tinh_tay_ninh', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Bình Dương', 'tinh_binh_duong', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Đồng Nai', 'tinh_dong_nai', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Bà Rịa - Vũng Tàu', 'tinh_ba_ria_vung_tau', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Thành phố Hồ Chí Minh', 'thanh_pho_ho_chi_minh', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Long An', 'tinh_long_an', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Tiền Giang', 'tinh_tien_giang', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Bến Tre', 'tinh_ben_tre', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Trà Vinh', 'tinh_tra_vinh', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Vĩnh Long', 'tinh_vinh_long', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Đồng Tháp', 'tinh_dong_thap', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh An Giang', 'tinh_an_giang', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Kiên Giang', 'tinh_kien_giang', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Thành phố Cần Thơ', 'thanh_pho_can_tho', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Hậu Giang', 'tinh_hau_giang', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Sóc Trăng', 'tinh_soc_trang', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Bạc Liêu', 'tinh_bac_lieu', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;
INSERT INTO provinces (name, code, created_at, updated_at) VALUES ('Tỉnh Cà Mau', 'tinh_ca_mau', NOW(), NOW()) ON CONFLICT (code) DO NOTHING;

DO $$ 
BEGIN 
  IF EXISTS(SELECT * FROM information_schema.columns WHERE table_name = 'stations' AND column_name = 'city') THEN 
    UPDATE stations s SET province_id = p.id FROM provinces p WHERE p.name LIKE '%' || s.city || '%'; 
    ALTER TABLE stations DROP COLUMN city; 
  END IF; 
  UPDATE stations SET province_id = (SELECT id FROM provinces LIMIT 1) WHERE province_id IS NULL; 
END $$;
